remote_theme: "mmistakes/minimal-mistakes@4.24.0"
lang: ko-KR
timezone: Asia/Seoul

title: 달리나음의 코스피 상대 강도
repository: dalinaum/turtle

plugins:
  - jekyll-include-cache
  - jekyll-feed

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-include-cache
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true